// front/components/footer/footer.jsx
import styles from './footer.module.scss';

import Link from 'next/link';

import { Small, Input } from 'components/typography';

const Footer = () => {
  return (
    <footer className={styles.Footer}>
      <Link href="/">
        <a>
          <Small>Melishev&#160;™</Small>
        </a>
      </Link>
      <Input>All rights reserved</Input>
    </footer>
  );
};

export default Footer;

// src/components/footer.vue
<template>
  <Grid tag="footer" :col="24">
    <Text variant="small">melishev / all rights reserved</Text>
  </Grid>
</template>

<script>
import { Grid, Text } from '@wuki-ui/vue';

export default {
  components: {
    Grid,
    Text,
  },
  setup() {

  },
};
</script>

<style lang="scss" scoped>
footer {
  height: 60px;
  display: flex;
  align-items: center;
  justify-content: space-between;
}
</style>
